/**
 * Canonical ordered inventory for the domain cutover (SIM-09A CUT-01).
 * The existing validate-domain-*.mjs entrypoints remain active until a later cutover.
 * Validator paths are relative to the repository root, not this directory.
 */
export const domainSuites = Object.freeze({
  "build-generated": Object.freeze({
    domain: "build/generated",
    title: "Build/generated",
    validators: Object.freeze([
      "validate-fragment-ownership.mjs",
      "validate-text-reader.mjs",
      "validate-ci-quality-scope.mjs",
      "validate.mjs",
      "validate-app-config.mjs",
      "validate-core-source-ownership.mjs",
      "validate-shared-core-route-ownership.mjs",
      "validate-asset-cache-policy.mjs",
      "validate-cache-policy.mjs",
      "validate-prebuilt-cache-model.mjs",
      "validate-tail-pagination.mjs",
      "validate-production-core-sources.mjs",
      "validate-generated-core-bindings.mjs",
    ]),
  }),
  "route-features": Object.freeze({
    domain: "route-features",
    title: "Route-features",
    validators: Object.freeze([
      "validate-global-search-results.mjs",
      "validate-global-search-agent-activation.mjs",
      "validate-global-search-open-lifecycle.mjs",
      "validate-global-search-keyboard.mjs",
      "validate-document-title-runtime.mjs",
      "validate-first-html-metadata.mjs",
      "validate-empty-states.mjs",
      "validate-entity-request-errors.mjs",
      "validate-home-search-recovery.mjs",
      "validate-evaluation-refresh-hydration.mjs",
      "validate-evaluation-stale-wallet-preferences-ui.mjs",
      "validate-settings-route-core.mjs",
      "validate-planner-route-core.mjs",
      "validate-planner-toolbar-actions.mjs",
      "validate-planner-saved-plan-actions.mjs",
      "validate-cross-domain-actions.mjs",
      "validate-planner-roster.mjs",
      "validate-settings-email-privacy.mjs",
      "validate-player-route-core.mjs",
      "validate-player-overall-loading-color.mjs",
      "validate-player-loading-plain-attributes.mjs",
      "validate-player-loading-unknown-position.mjs",
      "validate-render-reuse-contract.mjs",
      "validate-agent-title-loading.mjs",
      "validate-progression-retired-filter.mjs",
      "validate-watchlist-route-core.mjs",
      "validate-watchlist-progression-access.mjs",
      "validate-watchlist-selector-navigation.mjs",
    ]),
  }),
  "release-deployment": Object.freeze({
    domain: "release/deployment",
    title: "Release/deployment",
    validators: Object.freeze([
      "validate-release-history.mjs",
      "validate-release-version-source.mjs",
      "validate-release-runtime-ownership.mjs",
      "validate-runtime-data-identity.mjs",
      "validate-generated-styles.mjs",
      "validate-next-deployment-ownership.mjs",
      "validation/cross-release-cache-regression.mjs",
      "validate-database-refresh-deployment.mjs",
      "validate-security-boundaries.mjs",
      "validate-operational-health.mjs",
    ]),
  }),
  "api-persistence": Object.freeze({
    domain: "api/persistence",
    title: "API/persistence",
    validators: Object.freeze([
      "validate-shared-api-logic.mjs",
      "validate-request-body-limits.mjs",
      "validate-wallet-proof.mjs",
      "validate-wallet-challenge.mjs",
      "validate-wallet-session.mjs",
      "validate-wallet-session-integration.mjs",
      "validate-wallet-auth-rate-limit.mjs",
      "validate-wallet-mutation-origin.mjs",
      "validate-csp-report-only.mjs",
      "validate-vercel-security-headers.mjs",
      "validate-csp-legacy-script-hashes.mjs",
      "validate-csp-next-nonce.mjs",
      "validate-csp-legacy-eval-elimination.mjs",
      "validate-wallet-permission-cache.mjs",
      "validate-data-read-cache-policy.mjs",
      "validate-public-page-cache-policy.mjs",
      "validate-database-stats-ownership.mjs",
      "validate-my-clubs-data.mjs",
      "validate-supabase-persistence.mjs",
      "validate-supabase-private-grants.mjs",
      "validate-wallet-core.mjs",
      "validate-wallet-preferences-lifecycle.mjs",
      "validate-wallet-preference-write-scoping.mjs",
      "validate-evaluation-share-expiry.mjs",
      "validate-evaluation-share-preview.mjs",
      "validate-planner-persistence.mjs",
      "validate-shared-link-boundaries.mjs",
      "validate-share-api-fixtures.mjs",
      "validate-auth-boundary.mjs",
      "validate-evaluation-preview-portrait.mjs",
      "validate-evaluation-preview-rarity-accent.mjs",
      "validate-evaluation-preview-shell-path.mjs",
      "validate-bug-report.mjs",
    ]),
  }),
  "shared-ui": Object.freeze({
    domain: "shared-ui",
    title: "Shared UI",
    validators: Object.freeze([
      "validate-css-priority.mjs",
      "validate-runtime-style-ownership.mjs",
      "validate-sidebar-lifecycle-ownership.mjs",
      "validate-dropdown-style-ownership.mjs",
      "validate-dropdown-foundations.mjs",
      "validate-dropdown-trigger-open-highlight.mjs",
      "validate-filter-popup-interactions.mjs",
      "validate-active-filter-control.mjs",
      "validate-table-hover-scroll.mjs",
      "validate-control-style-ownership.mjs",
      "validate-toast-positioning.mjs",
      "validate-ui-foundations.mjs",
      "validate-behavior-foundations.mjs",
      "validate-shadow-foundations.mjs",
      "validate-ui-foundations-ownership.mjs",
      "validate-evaluation-mfl-usd-focus.mjs",
      "validate-css-ownership-consolidation.mjs",
      "validate-global-escape-ownership.mjs",
      "validate-motion-ownership.mjs",
      "validate-modal-entrance-lifecycle.mjs",
      "validate-dialog-foundations.mjs",
      "validate-z-index-ownership.mjs",
      "validate-nationality-flag-tooltips.mjs",
      "validate-checkbox-style.mjs",
      "validate-account-button-icon.mjs",
      "validate-theme-icons.mjs",
      "validate-footer-redesign.mjs",
      "validate-footer-creator-alignment.mjs",
      "validate-footer-loading-stability.mjs",
      "validate-privacy-page.mjs",
    ]),
  }),
  "responsive-ui": Object.freeze({
    domain: "responsive-ui",
    title: "Responsive UI",
    validators: Object.freeze([
      "validate-responsive-layout.mjs",
      "validate-responsive-reflow.mjs",
      "validate-intermediate-desktop-smoke-layout.mjs",
      "validate-responsive-header-label-fallback.mjs",
      "validate-mobile-box-press-shape.mjs",
      "validate-mobile-footer-floor.mjs",
      "validate-footer-route-coverage.mjs",
      "validate-player-mobile-scaling.mjs",
      "validate-player-note-first-paint.mjs",
      "validate-player-view-scroll-preservation.mjs",
      "validate-settings-mobile-actions.mjs",
      "validate-evaluation-mobile-first-paint.mjs",
      "validate-evaluation-responsive-player-names.mjs",
      "validate-stats-mobile-scaling.mjs",
      "validate-mobile-table-retry.mjs",
      "validate-mobile-progression-view-widths.mjs",
      "validate-mobile-table-compact-contract.mjs",
      "validate-small-screen-table-compaction.mjs",
      "validate-mobile-first-paint-cascade.mjs",
      "validate-mobile-header-first-paint-metrics.mjs",
      "validate-mobile-pager-scaling.mjs",
      "validate-mobile-selection-bar-scaling.mjs",
      "validate-changelog-responsive-scaling.mjs",
    ]),
  }),
  "routing-loading": Object.freeze({
    domain: "routing/loading",
    title: "Routing/loading",
    validators: Object.freeze([
      "validate-loading-ownership.mjs",
      "validate-data-shaped-loading-foundation.mjs",
      "validate-home-summary-first-paint.mjs",
      "validate-player-hero-club-branding.mjs",
      "validate-route-runtime.mjs",
      "validate-bootstrap-ownership.mjs",
      "validate-prebuilt-core-loading.mjs",
      "validate-route-core-startup-routing.mjs",
      "validate-route-page-normalization.mjs",
      "validate-route-shell-ownership.mjs",
      "validate-static-route-ui.mjs",
      "validate-wallet-opt-in-transition.mjs",
      "validate-protected-opted-out-routes.mjs",
      "validate-page-scroll-reset.mjs",
      "validate-view-button-refresh-handoff.mjs",
      "validate-generated-view-transition.mjs",
      "validate-page-route-gate-transition.mjs",
      "validate-table-loading-state.mjs",
      "validate-filter-loading-blank-rows.mjs",
      "validate-table-background-loading-stability.mjs",
      "validate-app-core-startup-handshake.mjs",
      "validate-data-client-foundation.mjs",
      "validate-client-performance-timing.mjs",
      "validate-performance-capture.mjs",
    ]),
  }),
  "evaluation": Object.freeze({
    domain: "evaluation",
    title: "Evaluation",
    validators: Object.freeze([
      "validate-eval-ownership.mjs",
      "validate-evaluation-search-lifecycle.mjs",
      "validation/evaluation-safari-result-tap.mjs",
      "validate-evaluation-search-fast-select.mjs",
      "validate-evaluation-search-clear-selection.mjs",
      "validate-evaluation-search-stacking.mjs",
      "validate-evaluation-load-cache.mjs",
      "validate-evaluation-route-ownership.mjs",
      "validate-evaluation-refresh-hydration.mjs",
      "validate-evaluation-overall-hover.mjs",
      "validate-evaluation-mfl-usd-edit-cancel.mjs",
      "validate-evaluation-mfl-usd-loading-race.mjs",
      "validate-evaluation-discount-derived-loading.mjs",
      "validate-evaluation-snapshot-edit-route.mjs",
      "validate-evaluation-saved-share-icon.mjs",
      "validate-progression-email-portrait.mjs",
    ]),
  }),
  "stats": Object.freeze({
    domain: "stats",
    title: "Stats",
    validators: Object.freeze([
      "validate-database-stats-lazy-runtime.mjs",
      "validate-stats-animation-owner.mjs",
      "validate-stats-navigation-lifecycle.mjs",
      "validate-mfl-stats-first-paint.mjs",
      "validate-mfl-stats-data-scope.mjs",
    ]),
  }),
  "club": Object.freeze({
    domain: "club",
    title: "Club",
    validators: Object.freeze([
      "validate-club-entry-workflow.mjs",
      "validate-club-refresh-startup.mjs",
      "validate-club-sorting.mjs",
      "validate-club-route-core.mjs",
      "validate-club-cache-ownership.mjs",
      "validate-club-title-loading.mjs",
    ]),
  }),
  "table": Object.freeze({
    domain: "table",
    title: "Table",
    validators: Object.freeze([
      "validate-table-route-core.mjs",
      "validate-pager-current-page.mjs",
      "validate-pager-cached-route-restore.mjs",
      "validate-single-page-pager-render-commit.mjs",
      "validate-table-column-layout.mjs",
      "validate-table-foundations.mjs",
      "validate-table-progression-spacing.mjs",
      "validate-table-row-vertical-centering.mjs",
      "validate-table-header-typography.mjs",
      "validate-mobile-sticky-name-column.mjs",
      "validate-table-filter-selection-lifecycle.mjs",
      "validate-filtered-empty-recovery.mjs",
      "validate-empty-onboarding.mjs",
      "validate-table-url-state.mjs",
      "validate-listing-column.mjs",
      "validate-marketplace-state-freshness.mjs",
      "validate-table-count-fast-path.mjs",
      "validate-player-table-actions.mjs",
      "validate-player-table-action-menu-rerender.mjs",
      "validate-player-table-action-menu-scroll.mjs",
      "validate-selection-action-menu-readiness.mjs",
      "validate-table-sort-session.mjs",
      "validate-progression-sorting.mjs",
      "validate-header-selection-loading.mjs",
      "validate-new-player-icon.mjs",
      "validate-progression-joined-agency-filter.mjs",
    ]),
  }),
});
